console.log("kneel js loaded");

const metals = [
  { metal: "Sterling Silver", price: 12.42 },
  { metal: "14K Gold", price: 736.4 },
  { metal: "24K Gold", price: 1258.9 },
  { metal: "Platinum", price: 795.45 },
  { metal: "Palladium", price: 1241.0 }
];

const diamonds = [
  { carats: 0.5, price: 405 },
  { carats: 0.75, price: 782 },
  { carats: 1, price: 1470 },
  { carats: 1.5, price: 1997 },
  { carats: 2, price: 3638 }
];

const ringStyles = [
  { style: "Classic", price: 500 },
  { style: "Modern", price: 710 },
  { style: "Vintage", price: 965 }
];

// need a function whose job is solely to take in all the different parameters
// and return a new object that represents the custom ring to be made, with a final price on it.

const createCustomRing = (style, carats, metal) => {
  return {
      style: style.style,
      carats: carats.carats,
      metal: metal.metal,
      price: metal.price + style.price + carats.price
  };
};

// Now when a customer places an order, and you want to build an HTML component to represent that order,
// you can use this new object generated by the factory function to do that.
const newRingOrder = createCustomRing(ringStyles[1], diamonds[2], metals[2]);

// Then add order to customer's shopping cart